#!/usr/bin/env python3

__version__ = '1.2'
__author__ = 'Camille Molenaar'
__opgave__ = 'w1o1.py'

def combine(arg1, arg2):
    sentence = arg1.strip() + " " + arg2.strip()
    return sentence.strip()

if __name__ == '__main__':
     print(combine("hello ", " world"))
     if combine("hello ", " world") != "hello world":
         print("Error\n")
